name: Build_Udpxy

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run:  cd chipmunk && make
    - name: upload
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{github.workspace}}
 
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download
      uses: actions/download-artifact@v3.0.0
    - name: archive
      uses: TheDoctor0/zip-release@0.6.2
    - name: gitrel
      uses: anton-yurchenko/git-release@v4.2.2





